apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchbase-admin-deployment
  labels:
    component: couchbase-server
    role: admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        component: couchbase-server
        name: couchbase-server
        role: admin
    spec:
      containers:
        - name: couchbase-server
          image: couchbase/server:enterprise-4.6.0
          ports:
            - name: admin
              containerPort: 8091
            - name: views
              containerPort: 8092
            - name: management
              containerPort: 11210
        - name: couchbase-sidekick
          image: tleyden5iwx/couchbase-cluster-go:latest
          command:
            - /bin/sh
            - -c
            - update-wrapper --skip-etcd-check couchbase-cluster start-couchbase-sidekick --discover-local-ip --etcd-servers http://etcd-cluster:2379
