apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler-worker-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: crawler-worker
    spec:
      containers:
      - name: crawler-worker
        image: korczis/microcrawler-worker:0.0.18
        args: ["--count", "16", "-u", "ws://crawler-webapp-service:4000/worker", "-a", "http://crawler-webapp-service:4000/api/v1/auth/signin", "--username", "korczis@gmail.com", "--password", "jindrisska"]

