apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler-webapp-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: crawler-webapp
    spec:
      containers:
      - name: crawler-webapp
        image: korczis/microcrawler-webapp:0.0.7
        imagePullPolicy: Always
        command: ["/start.sh"]
        ports:
        - containerPort: 4000
          name: restapi
          protocol: TCP
        env:
        - name: "MIX_ENV"
          value: "prod"
        - name: "PORT"
          value: "4000"
        - name: "AMQP_USERNAME"
          value: "username"
        - name: "AMQP_PASSWORD"
          value: "password"
        - name: "AMQP_HOSTNAME"
          value: "rabbitmq"
        - name: "GAUC_URL"
          value: "http://gauc-service:5000"
        - name: "ELASTIC_URL"
          value: "http://elastic:changeme@elasticsearch-service:9200"
        - name: "EXTERNAL_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.loadBalancer[0].ingress[0].ip
