apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler-webapp-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: crawler-webapp
    spec:
      containers:
      - name: crawler-webapp
        image: korczis/microcrawler-webapp:0.0.3
        command: ["/start.sh"]
        ports:
        - containerPort: 4000
          name: restapi
          protocol: TCP
        env:
        - name: "AMQP_USERNAME"
          value: "username"
        - name: "AMQP_PASSWORD"
          value: "password"
        - name: "AMQP_HOSTNAME"
          value: "rabbitmq"
        - name: "GAUC_URL"
          value: "http://gauc-service:5000"
        - name: "ELASTIC_URL"
          value: "http://elastic:changeme@elasticsearch-service:9200"
