apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
        imagePullPolicy: Always
        command: ["bin/elasticsearch"]
        args: [
          "-Ehttp.host=0.0.0.0",
          "-Etransport.host=_eth0:ipv4_",
          "-Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery",
          #"-Ediscovery.zen.ping.multicast.enabled=false",
          "-Ediscovery.zen.minimum_master_nodes=2",
          # "-Ediscovery.zen.hosts_provider=kubernetes",
          # "-Ecloud.kubernetes.service=elasticsearch-discovery",
          "-Ecluster.name=docker-cluster",
          "-Enetwork.bind_host=_eth0:ipv4_"
        ]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "docker-cluster"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        # https://www.elastic.co/guide/en/elasticsearch/plugins/current/intro.html
        - name: "ES_PLUGINS_INSTALL"
          value: "repository-gcs,x-pack,discovery-kubernetes"
        - name: "NETWORK_HOST"
          value: "_eth0:ipv4_"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
