apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: korczis/kibana:5.2.2-xpack
        ports:
        - containerPort: 5601
          name: webui
          protocol: TCP
        env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elastic:changeme@elasticsearch-service:9200"
