dependencies:
  - name: elasticsearch
    version: 0.1.0
    repository: file://charts/elasticsearch
  - name: grafana
    version: 0.1.0
    repository: file://charts/grafana
  - name: kibana
    version: 0.1.0
    repository: file://charts/kibana
  - name: weave
    version: 0.1.0
    repository: file://charts/weave