apiVersion: v1
data:
  default.tmpl: |-
{{.Files.Get "files/default.tmpl" | indent 4}}
  slack.tmpl: |-
{{.Files.Get "files/slack.tmpl" | indent 4}}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-templates
  namespace: monitoring