apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: {{ .Values.port.http }}
    protocol: TCP
