apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5601
          name: webui
          protocol: TCP
        env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elastic:changeme@elasticsearch-service:9200"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name