apiVersion: batch/v1
kind: Job
metadata:
  name: couchbase-set-password
  labels:
    app: couchbase
    component: set-password
spec:
  template:
    metadata:
      name: couchbase-set-password
      labels:
        app: couchbase
        component: set-password
    spec:
      containers:
      - name: couchbase-set-password
        image: giantswarm/tiny-tools
        command: ["/bin/sh", "-c"]
        env:
        - name: ETCD_SERVER
          value: {{ template "etcd.fullname" . }}
        - name: PASSWORD
          value: "password"
        command:
          - "/bin/sh"
          - "-ec"
          - |
            until curl -L "http://${ETCD_SERVER}:2379/v2/keys/couchbase.com/userpass" -X PUT -d value="couchbase:${PASSWORD}"; do
              echo "${ETCD_SERVER} is not ready yet, sleeping for 10 sec..."
              sleep 10
            done
      restartPolicy: Never
