apiVersion: v1
kind: Service
metadata:
  name: couchbase-admin-service
spec:
  ports:  # see http://docs.couchbase.com/admin/admin/Install/install-networkPorts.html
    - port: 8091
      name: admin
      targetPort: admin
#    - port: 8092
#      name: views
#      targetPort: views
#    - port: 8093
#      name: query
#      targetPort: query
#    - port: 8094
#      name: search
#      targetPort: search
#    - port: 9100
#      name: internal-admin
#      targetPort: internal-admin
#    - port: 9101
#      name: internal-scan
#      targetPort: internal-scan
#    - port: 9102
#      name: internal-http
#      targetPort: internal-http
#    - port: 9103
#      name: stream-init
#      targetPort: stream-init
#    - port: 9104
#      name: stream-catchup
#      targetPort: stream-catchup
#    - port: 9105
#      name: stream-mtnc
#      targetPort: stream-mtnc
#    - port: 9998
#      name: internal-rest
#      targetPort: internal-rest
#    - port: 9999
#      name: gsi
#      targetPort: gsi
#    - port: 11209
#      name: internal-bucket
#      targetPort: internal-bucket
#    - port: 11210
#      name: management
#      targetPort: management
#    - port: 11211
#      name: management-old
#      targetPort: management-old
#    - port: 11214
#      name: ssl-xdcr-1
#      targetPort: ssl-xdcr-1
#    - port: 11215
#      name: ssl-xdcr-2
#      targetPort: ssl-xdcr-2
#    - port: 18091
#      name: web-console-ssl
#      targetPort: web-console-ssl
#    - port: 18092
#      name: access-ssl
#      targetPort: access-ssl
#    - port: 18093
#      name: n1ql
#      targetPort: n1ql
  type: "LoadBalancer"
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    name: couchbase-server
    role: admin
