apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase-admin-deployment
  labels:
    component: couchbase-server
    role: admin
spec:
  serviceName: couchbase-admin
  replicas: 1
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        component: couchbase-server
        name: couchbase-server
        role: admin
    spec:
      containers:
        - name: couchbase-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: admin
              containerPort: 8091
            - name: views
              containerPort: 8092
            - name: management
              containerPort: 11210
          volumeMounts:
            - name: storage-couchbase-admin
              mountPath: /opt/var/couchbase

        - name: couchbase-sidekick
          image: tleyden5iwx/couchbase-cluster-go:latest
          env:
          - name: ETCD_SERVER
            value: {{ template "etcd.fullname" . }}
          command:
            - /bin/sh
            - -c
            - update-wrapper --skip-etcd-check couchbase-cluster start-couchbase-sidekick --discover-local-ip --etcd-servers http://${ETCD_SERVER}:2379
  volumeClaimTemplates:
    - metadata:
        name: storage-couchbase-admin
        annotations:
          volume.beta.kubernetes.io/storage-class: standard
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 32Gi
