apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
        imagePullPolicy: Always
        command: ["bin/elasticsearch"]
        args: [
          "-Ehttp.host=0.0.0.0",
          "-Etransport.host=_eth0:ipv4_",
          "-Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery",
          #"-Ediscovery.zen.ping.multicast.enabled=false",
          "-Ediscovery.zen.minimum_master_nodes=2",
          # "-Ediscovery.zen.hosts_provider=kubernetes",
          # "-Ecloud.kubernetes.service=elasticsearch-discovery",
          "-Ecluster.name=docker-cluster",
          "-Enetwork.bind_host=_eth0:ipv4_"
        ]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "docker-cluster"
        - name: NODE_MASTER
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        # https://www.elastic.co/guide/en/elasticsearch/plugins/current/intro.html
        - name: "ES_PLUGINS_INSTALL"
          value: "repository-gcs,x-pack"
        - name: "NETWORK_HOST"
          value: "_eth0:ipv4_"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 16Gi
