apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-scope
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-327a869",
        "original-request": {
          "url": "/k8s/v1.5/scope.yaml",
          "date": "Sat Aug 26 2017 19:25:17 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    name: weave-scope