apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase-server-deployment
  labels:
    component: couchbase-server
    role: nodes
spec:
  serviceName: couchbase-server
  replicas: 2
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: couchbase-server
        role: nodes
    spec:
      containers:
        - name: couchbase-server
          image: couchbase/server:enterprise-4.6.0
          ports:
            - name: admin
              containerPort: 8091
            - name: views
              containerPort: 8092
            - name: management
              containerPort: 11210
          volumeMounts:
            - name: storage-couchbase-server
              mountPath: /opt/var/couchbase
        - name: couchbase-sidekick
          image: tleyden5iwx/couchbase-cluster-go:latest
          command:
            - /bin/sh
            - -c
            - update-wrapper --skip-etcd-check couchbase-cluster start-couchbase-sidekick --discover-local-ip --etcd-servers http://etcd-cluster:2379
  volumeClaimTemplates:
    - metadata:
        name: storage-couchbase-server
        annotations:
          volume.beta.kubernetes.io/storage-class: standard
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 32Gi
