apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: crawler-webapp-ingress
spec:
  backend:
    serviceName: crawler-webapp-service
    servicePort: 4000
