apiVersion: v1
kind: Service
metadata:
  name: crawler-webapp-service
  labels:
    app: crawler-webapp
spec:
  ports:
    # the port that this service should serve on
  - port: 4000
    name: restapi
    targetPort: restapi
  selector:
    app: crawler-webapp
  type: "LoadBalancer"
