apiVersion: v1
kind: Service
metadata:
  name: nominatim-service
  labels:
    app: nominatim
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    app: nominatim
  type: "LoadBalancer"
