apiVersion: v1
kind: Service
metadata:
  name: gauc-service
  labels:
    app: gauc
spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    name: restapi
    targetPort: restapi
  selector:
    app: gauc
  type: "LoadBalancer"
