apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crawler-worker-scaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: crawler-worker-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
