apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - apollocrawler.com
    - goodcrawler.com
    secretName: kube-lego
  rules:
  - host: apollocrawler.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: crawler-webapp-service
          servicePort: 4000
      - path: /.well-known/acme-challenge/*
        backend:
          serviceName: kube-lego-gce
          servicePort: 8080
  - host: goodcrawler.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: crawler-webapp-service
          servicePort: 4000
      - path: /.well-known/acme-challenge/*
        backend:
          serviceName: kube-lego-gce
          servicePort: 8080
